### ISSUE TITLE
我应该怎样把登陆界面的密码输入框隐藏起来？

### ISSUE THREAD

**Issue by kdsrsl** [lijianying10/FixLinux#4]
隐藏起来或者设置成无法输入，变成不能通过密码登陆，谢谢.

**Comment by lijianying10** [comment]
兄弟你的问题我没明白啊。

**Comment by kdsrsl** [comment]
就是，开机之后输入密码那个界面，我想把输入密码的那个密码框隐藏起来，让人无法通过输入密码的方式登录系统。

发自我的 iPad

**Comment by lijianying10** [comment]
如果不输入密码的通过其他方式据我所知成本还是挺高的。
我记得可以刷身份卡
还有指纹识别。
